version: '3'

services:
    reverseproxy:
        image: marcoippel/reverseproxy:0.1
        ports:
            - 80:80
        restart: always
        container_name: reverseproxy

    web:
        depends_on:
            - reverseproxy
        image: marcoippel/web:0.1
        restart: always
        container_name: web

    api:
        depends_on:
            - reverseproxy
        image: marcoippel/api:0.1
        restart: always
        container_name: api